# Generated by Django 6.1.1 on 2026-09-27 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('tag_type', models.CharField(choices=[('Project', 'Production Project'), ('Prototype', 'Functional Prototype')], default='Project', max_length=20)),
                ('category', models.CharField(help_text='Enterprise, AI, Web, etc.', max_length=50)),
                ('domain', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('solution_statement', models.TextField()),
                ('technologies', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('architecture', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Case Study',
                'verbose_name_plural': 'Project Case Studies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company / Institution')),
                ('email', models.EmailField(max_length=150, verbose_name='Business Email')),
                ('phone_number', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must be valid.', regex='^[0-9+\\-\\s()]{7,18}$')], verbose_name='Phone Number')),
                ('service_required', models.CharField(choices=[('software', 'Custom Software Development'), ('web', 'Website & Web Applications (React / Next.js)'), ('app', 'Mobile App Development (Android & iOS)'), ('ai', 'AI & Machine Learning Solutions'), ('erp', 'ERP Solutions'), ('cloud', 'Cloud Hosting & DevOps Deployment'), ('api', 'API Development & Integration'), ('uiux', 'UI / UX Design'), ('qa', 'Testing & Quality Assurance'), ('consulting', 'IT Consulting')], max_length=40, verbose_name='Required Service')),
                ('project_description', models.TextField(verbose_name='Project Objectives & Scope')),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('REVIEW', 'In Technical Review'), ('CONTACTED', 'Client Contacted'), ('PROPOSAL', 'Proposal Sent'), ('CLOSED', 'Project Initiated / Closed')], default='NEW', max_length=20, verbose_name='Inquiry Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Project Inquiry',
                'verbose_name_plural': 'Project Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('number_label', models.CharField(default='01', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('technologies', models.JSONField(default=list, help_text='List of technology names')),
                ('capabilities', models.JSONField(default=list, help_text='List of core capabilities')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Offering',
                'verbose_name_plural': 'Service Offerings',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SolutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=120)),
                ('tag', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Solution Category',
                'verbose_name_plural': 'Solution Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database'), ('devops', 'DevOps & Cloud'), ('hosting', 'Hosting & Platforms')], max_length=30)),
                ('sublabel', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology Stack Item',
                'verbose_name_plural': 'Technology Stack Items',
                'ordering': ['category', 'order'],
            },
        ),
    ]
